In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.cross_validation import cross_val_score, ShuffleSplit
import numpy as np
from itertools import combinations
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
import time
import matplotlib.pyplot as plt
%matplotlib inline

c:\users\tim\anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
def import_data(experimental_file, response_file, response):
    'imports data'
    'experimental_file = experimental design csv filename i.e experimental.csv'
    'response_file = results csv filename i.e Response.csv'
    'response = reponse name: i.e rheomix final deg time min or rheomix stability time min'
    
    experimental_df = pd.read_csv(experimental_file)
    response_df = pd.read_csv(response_file)
    
    X = experimental_df[experimental_df.columns.values.tolist()[1:]].values
    y = response_df[response].values
    max1 = max(y)
    min1 = min(y)

    y_norm = [2*((i-min1)/(max1-min1)) - 1 for i in y]
    
    
    X_linear = X
    linear_terms = experimental_df.columns.values.tolist()[1:]
    
    return y_norm, X_linear, linear_terms, experimental_df, response_df
    

In [3]:
def X_gen(model, X_linear):

    for i, j in enumerate(model):
        
        if i == 0 and len(j) == 2: 
            X_new = X_linear[:, model[0][1]]
        
        else:
            
            if len(j) == 2:
                add = X_linear[:, j[1]]

            if len(j) == 3:
                add = X_linear[:, j[1]]*X_linear[:, j[2]]

            X_new2 = np.column_stack((X_new, add))
            X_new = X_new2

    
    return X_new

In [4]:
start = time.time()


# linear_terms = experimental_df.columns.values.tolist()[1:]



def fit_model(experimental_file, response_file, response, AIC_lim, CN_lim):
    

    total_subset = []
    model_subset = []
    
    y, X_linear, linear_terms, experimental_df, response_df = import_data(experimental_file, response_file, response)
    y1 = np.array(y)
    lin_terms = []
    AIC_prev = 1000

    for i in range(len(linear_terms)):
        term = linear_terms[i]
        key = i
        lin_terms.append([term, i])

    cnt = 0
    for i in range(len(lin_terms)):
        for j in combinations(lin_terms, i+1):
            linear_terms = list(j)


            model = [a for a in linear_terms]
            cnt+=1

            X = X_gen(model, X_linear)

            model_fit = sm.OLS(y, X)
            results = model_fit.fit()
            AIC_cur = results.aic
            
            if len(model) == 1:
                
                X1 = X.reshape(len(X), 1)
                model_obj = LinearRegression(fit_intercept=False)
                my_cv = ShuffleSplit(len(y1), n_iter=3, test_size=0.333, random_state=0)

                score = cross_val_score(model_obj, X1, y1, cv=my_cv)                
            
            else:
            
                model_obj = LinearRegression(fit_intercept=False)
                my_cv = ShuffleSplit(len(y1), n_iter=3, test_size=0.333, random_state=0)

                score = cross_val_score(model_obj, X, y1, cv=my_cv)

            print(score, model)
            
            model_name = '--'
            for i in model:
                
                model_name += i[0] + "--"

            dictionary = {'AIC': results.aic, 'Cond_No': results.condition_number, 'Model': model_name,
                          'r2': results.rsquared, 'No_terms': len(model), 'Kfold': score}
            total_subset.append(dictionary)
            
            if AIC_cur < AIC_lim:
                if results.condition_number < CN_lim:
                    
                    variables = model_fit.exog
                    
                    if len(model) != 1:

                        vif = [variance_inflation_factor(variables, i) for i in range(variables.shape[1])]
                        vif_max = max(vif)

                    else:
                        vif_max = 0


                    if max(vif) < 40:
                        dictionary = {'AIC': results.aic, 'Cond_No': results.condition_number, 'Model': model,
                        'r2': results.rsquared, 'No_terms': len(model), 'VIF': vif_max, 'Kfold': score}
                        
                        model_subset.append(dictionary)

                    
                    
            if AIC_cur < AIC_prev:

                AIC_prev = AIC_cur
                final_model = [model, results, AIC_cur]
                




            poss_terms = []
            for i in range(len(linear_terms)):
                for j in range(len(linear_terms)): 
                    if i < j:
                        poss_terms.append([linear_terms[i][0] + '*' + linear_terms[j][0],  linear_terms[i][1], linear_terms[j][1]])



            for m in range(1, len(poss_terms) + 1):
                for k in combinations(poss_terms, m):

                    model = [a for a in linear_terms]
                    for i in range(m):
                        model.append(k[i])

                    cnt +=1
                    X = X_gen(model, X_linear)

                    model_fit = sm.OLS(y, X)
                    results = model_fit.fit()
                    AIC_cur = results.aic
                    
                    model_obj = LinearRegression(fit_intercept=False)
                    my_cv = ShuffleSplit(len(y1), n_iter=3, test_size=0.333, random_state=0)
                    
                    score = cross_val_score(model_obj, X, y1, cv=my_cv)
                    print(score, model)
                    
                    
                    model_name = '--'
                    for i in model:

                        model_name += i[0] + "--"
                    
                    dictionary = {'AIC': results.aic, 'Cond_No': results.condition_number, 'Model': model_name,
                                  'r2': results.rsquared, 'No_terms': len(model), 'Kfold': score}
                    
                    total_subset.append(dictionary)



                    if AIC_cur < AIC_lim:
                        if results.condition_number < CN_lim:

                            variables = model_fit.exog
                            
                            if len(model) != 1:

                                vif = [variance_inflation_factor(variables, i) for i in range(variables.shape[1])]
                                vif_max = max(vif)

                            else:
                                vif_max = 0


                            if max(vif) < 40:
                                dictionary = {'AIC': results.aic, 'Cond_No': results.condition_number, 'Model': model,
                                'r2': results.rsquared, 'No_terms': len(model), 'VIF': vif_max, 'Kfold': score}
                                
                                model_subset.append(dictionary)


                    if AIC_cur < AIC_prev:
                        
                        AIC_prev = AIC_cur
                        final_model = [model, results, AIC_cur]




    return final_model, total_subset, model_subset


In [5]:
experimental_file = 'experimental.csv'
response_file = 'Response.csv'


test1 = 'rheomix final deg time min'
test2 = 'rheomix stability time min'
response = test1

AIC_lim = 20
CN_lim = 600


final_model, total_subset, model_subset = fit_model(experimental_file, response_file, response, AIC_lim, CN_lim)

[-0.07518123  0.04066424  0.00595714] [['Xpvc', 0]]
[-0.05665273 -0.24092534 -0.14585932] [['Xfiller', 1]]
[-0.57515999 -0.71887221 -0.40171308] [['Xfr', 2]]
[-0.37080128 -0.12605969 -0.21361922] [['Xstabiliser', 3]]
[-0.67173981 -0.70208221 -0.65447151] [['Xdinp', 4]]
[-0.84411323 -1.01356148 -1.12292237] [['Xldh', 5]]
[-1.00014419 -0.59635131 -0.37607724] [['Xsph', 6]]
[0.05828399 0.12315815 0.10136944] [['Xpvc', 0], ['Xfiller', 1]]
[0.05673939 0.16271353 0.14270511] [['Xpvc', 0], ['Xfiller', 1], ['Xpvc*Xfiller', 0, 1]]
[-0.07542445 -0.01784748  0.00319582] [['Xpvc', 0], ['Xfr', 2]]
[-0.12279031 -0.04051106 -0.02182254] [['Xpvc', 0], ['Xfr', 2], ['Xpvc*Xfr', 0, 2]]
[-0.07560192 -0.00051629  0.00469958] [['Xpvc', 0], ['Xstabiliser', 3]]
[-0.07719342 -0.01871565 -0.00331712] [['Xpvc', 0], ['Xstabiliser', 3], ['Xpvc*Xstabiliser', 0, 3]]
[0.11221871 0.21279414 0.15508477] [['Xpvc', 0], ['Xdinp', 4]]
[0.15797592 0.22854112 0.15961258] [['Xpvc', 0], ['Xdinp', 4], ['Xpvc*Xdinp', 0, 4]]
[0.0

[0.03406847 0.10149564 0.05499371] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xfr*Xldh', 2, 5]]
[-2.05833913  0.17512119  0.17191867] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xldh', 0, 5]]
[0.01623157 0.07722659 0.04458542] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xfr*Xldh', 2, 5]]
[-1.46757914  0.10690172  0.08487215] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xpvc*Xldh', 0, 5], ['Xfr*Xldh', 2, 5]]
[-2.04536587  0.16384774  0.13503573] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xldh', 0, 5], ['Xfr*Xldh', 2, 5]]
[-0.06430677 -0.05085534  0.00489202] [['Xpvc', 0], ['Xfr', 2], ['Xsph', 6]]
[-0.11028487 -0.05239251 -0.00983947] [['Xpvc', 0], ['Xfr', 2], ['Xsph', 6], ['Xpvc*Xfr', 0, 2]]
[-0.03350962 -0.03642476  0.01501062] [['Xpvc', 0], ['Xfr', 2], ['Xsph', 6], ['Xpvc*Xsph', 0, 6]]
[-0.17843133 -0.04996987 -0.01693282] [['Xpvc', 0], ['Xfr', 2], ['Xsph', 6], ['Xfr*Xsph', 2, 6]]
[-0.09473024 -0.04218762 -0.02329154] [['Xpvc', 0

[-0.02662604 -0.09265161 -0.15908847] [['Xfiller', 1], ['Xfr', 2], ['Xldh', 5], ['Xfr*Xldh', 2, 5]]
[ 0.12115711 -0.29983398 -0.433819  ] [['Xfiller', 1], ['Xfr', 2], ['Xldh', 5], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xldh', 1, 5]]
[ 0.03017694 -0.20512803 -0.37101643] [['Xfiller', 1], ['Xfr', 2], ['Xldh', 5], ['Xfiller*Xfr', 1, 2], ['Xfr*Xldh', 2, 5]]
[ 0.0426643  -0.15398411 -0.21404074] [['Xfiller', 1], ['Xfr', 2], ['Xldh', 5], ['Xfiller*Xldh', 1, 5], ['Xfr*Xldh', 2, 5]]
[ 0.0544822  -0.29026079 -0.45448009] [['Xfiller', 1], ['Xfr', 2], ['Xldh', 5], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xldh', 1, 5], ['Xfr*Xldh', 2, 5]]
[-0.16126685 -0.12195139  0.03500095] [['Xfiller', 1], ['Xfr', 2], ['Xsph', 6]]
[-0.10589242 -0.19103337 -0.09459369] [['Xfiller', 1], ['Xfr', 2], ['Xsph', 6], ['Xfiller*Xfr', 1, 2]]
[-0.12042229 -0.20211253  0.01213953] [['Xfiller', 1], ['Xfr', 2], ['Xsph', 6], ['Xfiller*Xsph', 1, 6]]
[-0.24632824 -0.05677855  0.10403949] [['Xfiller', 1], ['Xfr', 2], ['Xsph', 6], ['Xfr*Xsph',

[0.08497852 0.4559171  0.39232849] [['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfr*Xldh', 2, 5], ['Xdinp*Xldh', 4, 5]]
[0.0415074  0.44454366 0.39250191] [['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfr*Xdinp', 2, 4], ['Xfr*Xldh', 2, 5], ['Xdinp*Xldh', 4, 5]]
[-0.53293333 -0.46824398 -0.29299498] [['Xfr', 2], ['Xdinp', 4], ['Xsph', 6]]
[-0.33963186 -0.38338872 -0.10883056] [['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xfr*Xdinp', 2, 4]]
[-0.52582137 -0.28201333 -0.09263493] [['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xfr*Xsph', 2, 6]]
[ 0.0180376  -0.07216412 -0.06104829] [['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xdinp*Xsph', 4, 6]]
[-0.37953075 -0.27798103 -0.00257224] [['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xfr*Xdinp', 2, 4], ['Xfr*Xsph', 2, 6]]
[-0.06343602 -0.16967505 -0.10420664] [['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xfr*Xdinp', 2, 4], ['Xdinp*Xsph', 4, 6]]
[-0.13144716  0.01137895 -0.07264756] [['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xfr*Xsph', 2, 6], ['Xdinp*Xsph', 4, 6]]
[-0.204654

[ 0.08940974 -0.0357409   0.08145631] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xstabiliser', 1, 3]]
[0.18977465 0.19808148 0.22144125] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xstabiliser', 0, 3], ['Xfr*Xstabiliser', 2, 3]]
[ 0.02852771 -0.00138694  0.02535877] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xpvc*Xfiller', 0, 1], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3]]
[0.15910148 0.18549132 0.12741751] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xpvc*Xfiller', 0, 1], ['Xfiller*Xfr', 1, 2], ['Xfr*Xstabiliser', 2, 3]]
[0.18923603 0.15856514 0.14469219] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xpvc*Xfiller', 0, 1], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xstabiliser', 2, 3]]
[-0.13467697 -0.2092839  -0.02703707] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xpvc*Xfr', 

[0.04268477 0.19014754 0.01886614] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xdinp', 1, 4]]
[ 0.25492324 -0.46824706 -0.20840798] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xpvc*Xdinp', 0, 4], ['Xfr*Xdinp', 2, 4]]
[0.03464724 0.20928408 0.13857095] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4]]
[ 0.23390236 -0.0855466   0.13687955] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xfiller*Xfr', 1, 2], ['Xfr*Xdinp', 2, 4]]
[ 0.04223569 -0.05942631  0.18181241] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4]]
[0.20884943 0.10900982 0.14107306] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4]]
[ 0.17047247 -0.11193373  0.03163884] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xfr

[-0.0454382   0.14760038  0.0231663 ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xfr', 1, 2]]
[0.06866492 0.20192372 0.09123412] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xldh', 1, 5]]
[0.01707842 0.17451423 0.18886497] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfr*Xldh', 2, 5]]
[-2.77459124  0.321816    0.24401375] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xfr', 1, 2]]
[-2.07557265  0.44241407  0.35697937] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xldh', 1, 5]]
[-2.66089505  0.36505357  0.37780131] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xldh', 0, 5], ['Xfr*Xldh', 2, 5]]
[-0.04145608  0.13325698 -0.07890197] [['Xpvc',

[-0.03075373  0.04451126  0.13121238] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xsph', 6], ['Xpvc*Xfiller', 0, 1], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xsph', 1, 6]]
[-0.04420237  0.02017574  0.10940394] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xsph', 6], ['Xpvc*Xfiller', 0, 1], ['Xfiller*Xfr', 1, 2], ['Xfr*Xsph', 2, 6]]
[-0.16181424  0.11398247  0.1574701 ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xsph', 6], ['Xpvc*Xfiller', 0, 1], ['Xfiller*Xsph', 1, 6], ['Xfr*Xsph', 2, 6]]
[0.12914499 0.10622192 0.11978449] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xsph', 6], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xsph', 0, 6], ['Xfiller*Xfr', 1, 2]]
[0.25377307 0.34545759 0.26594718] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xsph', 6], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xsph', 0, 6], ['Xfiller*Xsph', 1, 6]]
[-0.16287236  0.23198421  0.21252665] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xsph', 6], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xsph', 0, 6], ['Xfr*Xsph', 2, 6]]
[0.02832033 0.04615072 0.10269116] [['Xpvc', 0], ['X

[ 0.24535236 -0.32834876 -0.01347266] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xdinp', 3, 4]]
[-0.01331166 -0.45185295 -0.3738763 ] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xdinp', 1, 4], ['Xstabiliser*Xdinp', 3, 4]]
[-0.09647474  0.13579565 -0.03430409] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4]]
[ 0.26396995 -0.31785679 -0.031508  ] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.12520983 -0.43375544 -0.41367787] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xdinp', 1, 4], ['Xstabiliser*Xdinp', 3, 4]]
[-0.04715508 -0.42970158 -0.42666246] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 

[-0.85581789  0.35884499  0.3702163 ] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xldh', 3, 5]]
[-0.36047437  0.41646052  0.5059884 ] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xldh', 1, 5], ['Xstabiliser*Xldh', 3, 5]]
[-2.25248305  0.42359891  0.3548762 ] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xldh', 1, 5]]
[-1.70268269  0.45251651  0.48067576] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xldh', 3, 5]]
[-0.53243504  0.56368013  0.71209527] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xldh', 1, 5], ['Xstab

[-0.1570003   0.04057304  0.12662337] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xsph', 6], ['Xpvc*Xfiller', 0, 1], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xsph', 1, 6], ['Xstabiliser*Xsph', 3, 6]]
[0.22839263 0.1010145  0.25567235] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xsph', 6], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xsph', 0, 6], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xsph', 1, 6]]
[0.09828807 0.062193   0.1471539 ] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xsph', 6], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xsph', 0, 6], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xsph', 3, 6]]
[0.18899285 0.1066763  0.17474358] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xsph', 6], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xsph', 0, 6], ['Xfiller*Xsph', 1, 6], ['Xstabiliser*Xsph', 3, 6]]
[0.10929773 0.11602511 0.15093308] [['Xpvc', 0], ['Xfiller', 1], ['Xstabiliser', 3], ['Xsph', 6], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xsph', 1, 6], ['Xs

[-1.21391933  0.60721643  0.56953685] [['Xpvc', 0], ['Xfiller', 1], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xdinp', 0, 4], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xdinp', 1, 4], ['Xfiller*Xldh', 1, 5], ['Xdinp*Xldh', 4, 5]]
[0.2643694  0.27304636 0.26626689] [['Xpvc', 0], ['Xfiller', 1], ['Xdinp', 4], ['Xsph', 6]]
[0.23640556 0.27761231 0.25920087] [['Xpvc', 0], ['Xfiller', 1], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xfiller', 0, 1]]
[0.29255815 0.29660625 0.29063806] [['Xpvc', 0], ['Xfiller', 1], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xdinp', 0, 4]]
[0.28335968 0.24905917 0.27568123] [['Xpvc', 0], ['Xfiller', 1], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xsph', 0, 6]]
[0.14480514 0.2696477  0.1706997 ] [['Xpvc', 0], ['Xfiller', 1], ['Xdinp', 4], ['Xsph', 6], ['Xfiller*Xdinp', 1, 4]]
[0.17182955 0.29041728 0.27863548] [['Xpvc', 0], ['Xfiller', 1], ['Xdinp', 4], ['Xsph', 6], ['Xfiller*Xsph', 1, 6]]
[0.15514872 0.18207248 0.25682706] [['Xpvc', 0], ['Xfiller', 1], ['Xdinp', 4], ['Xsph', 6], ['Xdinp

[-0.17328838  0.22724496  0.21922439] [['Xpvc', 0], ['Xfiller', 1], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xfiller', 0, 1], ['Xfiller*Xldh', 1, 5]]
[-0.09732974  0.22077665  0.25619777] [['Xpvc', 0], ['Xfiller', 1], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xfiller', 0, 1], ['Xfiller*Xsph', 1, 6]]
[-0.28610515  0.18433172  0.24358463] [['Xpvc', 0], ['Xfiller', 1], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xfiller', 0, 1], ['Xldh*Xsph', 5, 6]]
[-2.33898965  0.40721057  0.45468535] [['Xpvc', 0], ['Xfiller', 1], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xpvc*Xsph', 0, 6]]
[-1.00338426  0.49820935  0.59459646] [['Xpvc', 0], ['Xfiller', 1], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xldh', 1, 5]]
[-1.92447607  0.38278216  0.44102212] [['Xpvc', 0], ['Xfiller', 1], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xsph', 1, 6]]
[-1.90172389  0.354803    0.41389642] [['Xpvc', 0], ['Xfiller', 1], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xldh*Xsph', 5, 6]]
[0.01000499 0.24729476 0.28

[-1.84519299  0.40953468  0.5004809 ] [['Xpvc', 0], ['Xfiller', 1], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xpvc*Xsph', 0, 6], ['Xfiller*Xldh', 1, 5], ['Xfiller*Xsph', 1, 6], ['Xldh*Xsph', 5, 6]]
[-1.77073828  0.39146628  0.50281588] [['Xpvc', 0], ['Xfiller', 1], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xldh', 0, 5], ['Xpvc*Xsph', 0, 6], ['Xfiller*Xldh', 1, 5], ['Xfiller*Xsph', 1, 6], ['Xldh*Xsph', 5, 6]]
[0.09107539 0.16088223 0.15826148] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4]]
[0.15234401 0.18009709 0.18462117] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2]]
[0.1251524  0.17646862 0.19896139] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3]]
[0.14291276 0.18604883 0.15101187] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xdinp', 0, 4]]
[0.13087289 0.20184407 0.17441164] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfr*Xstabiliser', 2

[ 0.31192269 -0.14256531  0.0093554 ] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.19920687 -0.31173445 -0.06504467] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4]]
[ 0.26313304 -0.13573103  0.10955068] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.21597582 -0.19374973 -0.02180428] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.28249256 -0.13358849  0.02872623] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.

[-1.6580176   0.25540608  0.20946529] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xldh', 0, 5], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xldh', 2, 5], ['Xstabiliser*Xldh', 3, 5]]
[-1.635778    0.18327704  0.21425649] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xldh', 2, 5], ['Xstabiliser*Xldh', 3, 5]]
[-1.87733442  0.24050892  0.20471687] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xldh', 2, 5], ['Xstabiliser*Xldh', 3, 5]]
[-0.10513405 -0.05281996  0.00447816] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xsph', 6]]
[-0.11417584 -0.05289282 -0.01400887] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xsph', 6], ['Xpvc*Xfr', 0, 2]]
[-0.10549205 -0.1384241   0.00795842] [['Xpvc', 0], ['Xfr', 2], ['Xstabiliser', 3], ['Xsph', 6], ['Xpvc*Xstabil

[-1.04645832  0.25409186  0.292196  ] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xldh', 0, 5]]
[0.14244434 0.10045069 0.21818533] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfr*Xdinp', 2, 4]]
[0.15285704 0.26930475 0.27118286] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfr*Xldh', 2, 5]]
[0.24651555 0.64383398 0.60476515] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xdinp*Xldh', 4, 5]]
[0.20735823 0.32644586 0.38017068] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4]]
[-1.3304392   0.36012479  0.42022243] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xldh', 0, 5]]
[0.23150813 0.09748855 0.28187379] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xfr*Xdinp', 2, 4]]
[0.2411743  0.33551635 0.38466161] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xfr*Xldh', 2, 5]]
[0.19152992 0.65584557 0.63135214] [['Xpvc

[0.01996743 0.02402128 0.16017131] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xfr*Xsph', 2, 6], ['Xdinp*Xsph', 4, 6]]
[0.07409474 0.16001913 0.18333272] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xpvc*Xsph', 0, 6]]
[ 0.16182169 -0.43544886 -0.17638403] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xfr*Xdinp', 2, 4]]
[-0.01338974  0.16576772  0.16250757] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xfr*Xsph', 2, 6]]
[0.01490174 0.0277576  0.18180349] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xdinp*Xsph', 4, 6]]
[ 0.08131031 -0.2757039   0.01526469] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xsph', 0, 6], ['Xfr*Xdinp', 2, 4]]
[-0.12926448  0.16662778  0.17462992] [['Xpvc', 0], ['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xfr', 0, 

[0.009036   0.05343506 0.0569148 ] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xfr', 0, 2], ['Xfr*Xldh', 2, 5]]
[-0.13676872  0.08678663  0.0609241 ] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xfr', 0, 2], ['Xfr*Xsph', 2, 6]]
[-0.02060243  0.0504764   0.10202044] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xfr', 0, 2], ['Xldh*Xsph', 5, 6]]
[-2.24820692  0.12782133  0.17253995] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xpvc*Xsph', 0, 6]]
[-1.27578381  0.09829107  0.10851484] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xfr*Xldh', 2, 5]]
[-1.30589821  0.13793039  0.16818836] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xfr*Xsph', 2, 6]]
[-1.63001136  0.1000143   0.17903323] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xldh*Xsph', 5, 6]]
[0.04167338 0.05771742 0.07622771] [['Xpvc', 0], ['Xfr', 2], ['Xldh', 5], ['Xsph', 6],

[0.26420505 0.41545389 0.44932481] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3]]
[0.23767946 0.32298541 0.35803192] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xdinp', 0, 4]]
[-1.33065635  0.27800197  0.30374226] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xldh', 0, 5]]
[0.27545266 0.22612013 0.23982876] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xstabiliser*Xdinp', 3, 4]]
[-0.00290955  0.42821216  0.46202021] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xstabiliser*Xldh', 3, 5]]
[0.25600891 0.63009111 0.66028146] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xdinp*Xldh', 4, 5]]
[0.26403451 0.27594893 0.41013314] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4]]
[-1.4650475   0.44732106  0.49339661] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xstabiliser', 0,

[-0.4156584   0.45610356  0.6502326 ] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xpvc*Xldh', 0, 5], ['Xstabiliser*Xdinp', 3, 4], ['Xdinp*Xldh', 4, 5]]
[0.19529969 0.56567929 0.72094475] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xpvc*Xldh', 0, 5], ['Xstabiliser*Xldh', 3, 5], ['Xdinp*Xldh', 4, 5]]
[0.21138973 0.62407134 0.72199012] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xldh', 3, 5], ['Xdinp*Xldh', 4, 5]]
[0.19872665 0.60207943 0.72874092] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xldh', 3, 5], ['Xdinp*Xldh', 4, 5]]
[0.17253574 0.6069353  0.71877042] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xpvc*Xdinp', 0,

[ 0.21980758 -0.15817024 -0.04459406] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xsph', 0, 6], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xsph', 3, 6]]
[ 0.0976339  -0.17066464  0.06721799] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xsph', 0, 6], ['Xstabiliser*Xdinp', 3, 4], ['Xdinp*Xsph', 4, 6]]
[-0.02438307 -0.05112704  0.12321953] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xsph', 0, 6], ['Xstabiliser*Xsph', 3, 6], ['Xdinp*Xsph', 4, 6]]
[ 0.10669236 -0.11457549  0.05719874] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xstabiliser', 0, 3], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xsph', 3, 6], ['Xdinp*Xsph', 4, 6]]
[ 0.20721963 -0.12625147 -0.02068557] [['Xpvc', 0], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xpvc*Xdinp', 0, 4], ['Xpvc*Xsph', 0, 6], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xsph', 

[ 0.00241953  0.03137662 -0.01186758] [['Xpvc', 0], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xsph', 0, 6], ['Xstabiliser*Xsph', 3, 6], ['Xldh*Xsph', 5, 6]]
[-0.40129329  0.16998957  0.06460057] [['Xpvc', 0], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xstabiliser*Xldh', 3, 5], ['Xstabiliser*Xsph', 3, 6], ['Xldh*Xsph', 5, 6]]
[-4.75094695  0.2061479   0.27682712] [['Xpvc', 0], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xpvc*Xsph', 0, 6], ['Xstabiliser*Xldh', 3, 5]]
[-5.70831023  0.07619213  0.10509986] [['Xpvc', 0], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xpvc*Xsph', 0, 6], ['Xstabiliser*Xsph', 3, 6]]
[-5.38479733  0.11014673  0.24819313] [['Xpvc', 0], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xpvc*Xsph', 0, 6], ['Xldh*Xsph', 5, 6]]
[-2.7533335   0.21366026  0.10575072] [['Xpvc', 0], ['Xstabiliser', 3], ['Xl

[-1.44913204  0.28350002  0.4036482 ] [['Xpvc', 0], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xpvc*Xsph', 0, 6], ['Xdinp*Xsph', 4, 6]]
[-2.17142168  0.25325405  0.33955686] [['Xpvc', 0], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xpvc*Xsph', 0, 6], ['Xldh*Xsph', 5, 6]]
[-0.35509026  0.62027075  0.6119213 ] [['Xpvc', 0], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xdinp*Xldh', 4, 5], ['Xdinp*Xsph', 4, 6]]
[-0.94564224  0.57075566  0.61705295] [['Xpvc', 0], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xdinp*Xldh', 4, 5], ['Xldh*Xsph', 5, 6]]
[-0.82923588  0.21760437  0.37931427] [['Xpvc', 0], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xldh', 0, 5], ['Xdinp*Xsph', 4, 6], ['Xldh*Xsph', 5, 6]]
[0.23131708 0.61447732 0.62678671] [['Xpvc', 0], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xpvc*Xsph', 0, 6], ['Xdinp*Xldh', 4, 5], ['Xdinp*Xsph', 4, 6]]
[0.12749599 0.57022904 0.653118  ] [['Xpvc', 0], ['Xdinp', 4], ['X

[ 0.07708857 -0.0729367  -0.12090901] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xstabiliser', 2, 3]]
[ 0.056263   -0.11419873 -0.05928768] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xdinp', 2, 4]]
[ 0.34335709 -0.26349785 -0.06942275] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xdinp', 3, 4]]
[-0.01195391 -0.17350964 -0.1487008 ] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3]]
[-0.0268751  -0.26076816 -0.09744977] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4]]
[ 0.14285094 -0.30892571 -0.17335275] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfiller*X

[ 0.01750576  0.00170791 -0.10625251] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xldh', 2, 5]]
[-0.12142049 -0.02720691 -0.09157172] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xldh', 3, 5]]
[-0.292733   -0.02295785 -0.16232594] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfiller*Xldh', 1, 5], ['Xfr*Xstabiliser', 2, 3]]
[-0.10355691 -0.00435243 -0.12318714] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfiller*Xldh', 1, 5], ['Xfr*Xldh', 2, 5]]
[-0.16852441 -0.02135026 -0.15752179] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfiller*Xldh', 1, 5], ['Xstabiliser*Xldh', 3, 5]]
[-0.02095952 -0.06798333 -0.08334272] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xldh', 2, 5]]
[-0.16575428 -0.07648937 -0.1092456 ] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 

[-0.28401313 -0.13104765 -0.04081979] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xsph', 6], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3]]
[-0.26754779 -0.1169145  -0.02469979] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xsph', 6], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xsph', 1, 6]]
[-0.34702707 -0.02418262  0.01275855] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xsph', 6], ['Xfiller*Xfr', 1, 2], ['Xfr*Xstabiliser', 2, 3]]
[-0.22555628 -0.08988373 -0.07760152] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xsph', 6], ['Xfiller*Xfr', 1, 2], ['Xfr*Xsph', 2, 6]]
[-0.23399774 -0.15351831 -0.01821703] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xsph', 6], ['Xfiller*Xfr', 1, 2], ['Xstabiliser*Xsph', 3, 6]]
[-0.31559558 -0.11838419  0.02740506] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xsph', 6], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xsph', 1, 6]]
[-0.37643371 -0.05632118  0.05608331] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xsph', 6], 

[-0.36204155 -0.16091631  0.01133488] [['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xsph', 6], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xsph', 1, 6], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xsph', 2, 6], ['Xstabiliser*Xsph', 3, 6]]
[-0.03703982 -0.23890153 -0.31336237] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5]]
[ 0.02331515 -0.23800617 -0.44351274] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xfr', 1, 2]]
[ 0.13945898 -0.1980666  -0.35233741] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xdinp', 1, 4]]
[ 0.00609558 -0.2085729  -0.35513457] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xldh', 1, 5]]
[-0.05496089 -0.16449955 -0.32630633] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfr*Xdinp', 2, 4]]
[-0.03627953 -0.23235034 -0.15343513] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfr*Xldh', 2, 5]]
[0.13381325 0.40536368 0.53628822] [['Xfiller', 1], ['Xfr', 2], ['Xdin

[-0.05226029  0.24785538  0.45353641] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xldh', 1, 5], ['Xfr*Xdinp', 2, 4], ['Xfr*Xldh', 2, 5], ['Xdinp*Xldh', 4, 5]]
[ 0.00703959 -0.63694791 -0.2726666 ] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfiller*Xldh', 1, 5], ['Xfr*Xdinp', 2, 4], ['Xfr*Xldh', 2, 5]]
[0.12061197 0.50735048 0.52197455] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfiller*Xldh', 1, 5], ['Xfr*Xdinp', 2, 4], ['Xdinp*Xldh', 4, 5]]
[0.1010828  0.38505773 0.51603135] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfiller*Xldh', 1, 5], ['Xfr*Xldh', 2, 5], ['Xdinp*Xldh', 4, 5]]
[-0.00314842  0.37011393  0.52154046] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4], ['Xfr*Xldh', 2, 5], ['Xdinp*Xldh', 4, 

[-0.27302585 -0.28128628  0.04096338] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xfiller*Xfr', 1, 2], ['Xfr*Xdinp', 2, 4], ['Xfr*Xsph', 2, 6], ['Xdinp*Xsph', 4, 6]]
[-0.25653505 -0.36518151 -0.21637444] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xfiller*Xdinp', 1, 4], ['Xfiller*Xsph', 1, 6], ['Xfr*Xdinp', 2, 4], ['Xfr*Xsph', 2, 6]]
[ 0.05866554 -0.31744805 -0.11484495] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xfiller*Xdinp', 1, 4], ['Xfiller*Xsph', 1, 6], ['Xfr*Xdinp', 2, 4], ['Xdinp*Xsph', 4, 6]]
[-0.08761568 -0.05956831 -0.14292308] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xfiller*Xdinp', 1, 4], ['Xfiller*Xsph', 1, 6], ['Xfr*Xsph', 2, 6], ['Xdinp*Xsph', 4, 6]]
[-0.09068986 -0.26266068 -0.15048869] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['Xsph', 6], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4], ['Xfr*Xsph', 2, 6], ['Xdinp*Xsph', 4, 6]]
[-0.12482686 -0.19867737 -0.07003917] [['Xfiller', 1], ['Xfr', 2], ['Xdinp', 4], ['

[-0.26538698 -0.14244659 -0.17988633] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xstabiliser*Xldh', 3, 5]]
[0.18003243 0.53431946 0.63599109] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xdinp*Xldh', 4, 5]]
[-0.0117232  -0.13692934 -0.26210872] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4]]
[-0.3187422   0.06887791 -0.13904206] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xldh', 1, 5]]
[ 0.33885996 -0.14514502 -0.00750312] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xdinp', 3, 4]]
[-0.23024339 -0.07477312 -0.15355862] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xldh', 3, 5]]
[0.12378924 0.53357053 0.63700063] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xs

[0.2120689  0.52417877 0.60961654] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xldh', 3, 5], ['Xdinp*Xldh', 4, 5]]
[0.07843762 0.45533333 0.63524656] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xldh', 1, 5], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xldh', 3, 5], ['Xdinp*Xldh', 4, 5]]
[0.16061948 0.51334097 0.59163684] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xdinp', 1, 4], ['Xfiller*Xldh', 1, 5], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xldh', 3, 5], ['Xdinp*Xldh', 4, 5]]
[0.14379055 0.51251544 0.57502756] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfiller*Xldh', 1, 5], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xldh', 3, 5], ['Xdinp*Xldh', 4, 5]]
[-0.27536378  0.08790099  0.07568251] [['Xfiller

[ 0.09172532 -0.2587651  -0.02524909] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xsph', 1, 6], ['Xstabiliser*Xdinp', 3, 4], ['Xdinp*Xsph', 4, 6]]
[-0.26327163 -0.0373213   0.03551144] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xsph', 1, 6], ['Xstabiliser*Xsph', 3, 6], ['Xdinp*Xsph', 4, 6]]
[ 0.00762524 -0.23486031  0.00066392] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xsph', 3, 6], ['Xdinp*Xsph', 4, 6]]
[-0.101693   -0.23527328 -0.1719157 ] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xfiller*Xdinp', 1, 4], ['Xfiller*Xsph', 1, 6], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xsph', 3, 6]]
[ 0.09150998 -0.3205374  -0.14347902] [['Xfiller', 1], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xfiller*Xdinp', 1, 4], ['Xfiller*Xsph', 1, 6], ['Xstabiliser*

[-0.62790185 -0.04131551 -0.04728288] [['Xfiller', 1], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xfiller*Xsph', 1, 6], ['Xstabiliser*Xsph', 3, 6], ['Xldh*Xsph', 5, 6]]
[-1.84594319 -0.05490203 -0.13869561] [['Xfiller', 1], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xstabiliser*Xldh', 3, 5], ['Xstabiliser*Xsph', 3, 6], ['Xldh*Xsph', 5, 6]]
[-3.95297084 -0.06247006 -0.08248154] [['Xfiller', 1], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xldh', 1, 5], ['Xfiller*Xsph', 1, 6], ['Xstabiliser*Xldh', 3, 5]]
[-2.91240642 -0.07506684 -0.11938482] [['Xfiller', 1], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xldh', 1, 5], ['Xfiller*Xsph', 1, 6], ['Xstabiliser*Xsph', 3, 6]]
[-2.88440393  0.06671763  0.0462104 ] [['Xfiller', 1], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xldh', 1, 5], ['Xfiller*Xsph', 1, 6], ['Xldh*Xsph', 5, 6]]
[-3.79170818 -0.08708734 -0.135

[0.18358663 0.51097637 0.5765729 ] [['Xfiller', 1], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xfiller*Xldh', 1, 5], ['Xfiller*Xsph', 1, 6], ['Xdinp*Xldh', 4, 5]]
[-0.40344264  0.06350675  0.13546682] [['Xfiller', 1], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xfiller*Xldh', 1, 5], ['Xfiller*Xsph', 1, 6], ['Xdinp*Xsph', 4, 6]]
[-0.74400564 -0.20917981 -0.11017218] [['Xfiller', 1], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xfiller*Xldh', 1, 5], ['Xfiller*Xsph', 1, 6], ['Xldh*Xsph', 5, 6]]
[0.29817058 0.61467661 0.64374585] [['Xfiller', 1], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xfiller*Xldh', 1, 5], ['Xdinp*Xldh', 4, 5], ['Xdinp*Xsph', 4, 6]]
[-0.34799049  0.53369566  0.56695073] [['Xfiller', 1], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xfiller*Xldh', 1, 5], ['Xdinp*Xldh', 4, 5], ['Xldh*Xsph', 5, 6]]
[-0.50513844  0.18193048  0.13861054] [['Xfiller', 1], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xfiller*Xldh', 1, 5], ['Xdinp*Xsph', 4, 6], ['Xldh*Xsph', 5, 6]]
[0.2839131  0.56207557 0.

[0.15335784 0.54675264 0.52422741] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xdinp*Xldh', 4, 5]]
[0.2675025  0.04864951 0.13098192] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xldh', 2, 5], ['Xstabiliser*Xdinp', 3, 4]]
[-0.36616368 -0.29822076 -0.31788028] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xldh', 2, 5], ['Xstabiliser*Xldh', 3, 5]]
[0.1218795  0.48277261 0.45629827] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xldh', 2, 5], ['Xdinp*Xldh', 4, 5]]
[0.12844993 0.07626389 0.10637667] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xldh', 3, 5]]
[0.22679159 0.64296666 0.65921922] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4

[-0.41292462 -0.28060961 -0.06832019] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xfr*Xdinp', 2, 4], ['Xdinp*Xsph', 4, 6]]
[0.06888616 0.02025996 0.04525879] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xfr*Xsph', 2, 6], ['Xstabiliser*Xdinp', 3, 4]]
[-0.27018608 -0.13790104 -0.013124  ] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xfr*Xsph', 2, 6], ['Xstabiliser*Xsph', 3, 6]]
[-0.21681818 -0.09142631 -0.08224371] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xfr*Xsph', 2, 6], ['Xdinp*Xsph', 4, 6]]
[0.07820222 0.00699755 0.06772161] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xsph', 3, 6]]
[ 0.26041085 -0.06625963  0.10477951] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xstabiliser*Xdinp', 3, 4], ['Xdinp*Xsph', 4, 6]]
[-0.17930146 -0.33229016 -0.03280619] [['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xsph', 6], ['Xstabiliser*Xsph', 3, 6], ['

[-0.55641665 -0.22214981 -0.25302486] [['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xsph', 3, 6]]
[-0.41643309 -0.11057362 -0.13093625] [['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xfr*Xstabiliser', 2, 3], ['Xldh*Xsph', 5, 6]]
[-0.57314077 -0.24708081 -0.13083196] [['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xfr*Xldh', 2, 5], ['Xfr*Xsph', 2, 6]]
[-0.73893799 -0.34265024 -0.18289877] [['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xfr*Xldh', 2, 5], ['Xstabiliser*Xldh', 3, 5]]
[-0.56252401 -0.35076707 -0.29027957] [['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xfr*Xldh', 2, 5], ['Xstabiliser*Xsph', 3, 6]]
[-0.43020038 -0.20420964 -0.16778575] [['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xfr*Xldh', 2, 5], ['Xldh*Xsph', 5, 6]]
[-0.74793399 -0.16657517 -0.19344554] [['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xsph', 6], ['Xfr*Xsph', 2, 6], ['Xstabiliser*Xldh', 

[-0.55400766 -0.46911834 -0.46430668] [['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6]]
[-0.44197963 -0.33691496 -0.25785051] [['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xfr*Xdinp', 2, 4]]
[-0.56985029 -0.55653453 -0.35343593] [['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xfr*Xldh', 2, 5]]
[-0.55333924 -0.26720629 -0.24136603] [['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xfr*Xsph', 2, 6]]
[0.18995154 0.53935503 0.5021295 ] [['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xdinp*Xldh', 4, 5]]
[0.0213502  0.0549796  0.05296875] [['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xdinp*Xsph', 4, 6]]
[-0.37247449 -0.37481739 -0.4049824 ] [['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xldh*Xsph', 5, 6]]
[-0.54467607 -0.43640281 -0.04179789] [['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xfr*Xdinp', 2, 4], ['Xfr*Xldh', 2, 5]]
[-0.43804714 -0.16386968 -0.11200217] [['Xfr', 2], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xfr*Xdinp', 2, 4],

[-0.3807658  -0.07024066  0.11671151] [['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xstabiliser*Xldh', 3, 5], ['Xdinp*Xsph', 4, 6]]
[-0.38249748 -0.13930179 -0.06657253] [['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xstabiliser*Xldh', 3, 5], ['Xldh*Xsph', 5, 6]]
[0.19361549 0.51966841 0.62621895] [['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xstabiliser*Xsph', 3, 6], ['Xdinp*Xldh', 4, 5]]
[-0.23020834 -0.04966507  0.0333162 ] [['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xstabiliser*Xsph', 3, 6], ['Xdinp*Xsph', 4, 6]]
[-0.3417345  -0.06884994 -0.12711316] [['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xstabiliser*Xsph', 3, 6], ['Xldh*Xsph', 5, 6]]
[0.25265923 0.57683805 0.64409291] [['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xdinp*Xldh', 4, 5], ['Xdinp*Xsph', 4, 6]]
[0.18454117 0.56082774 0.64627195] [['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xdinp*Xldh', 4, 5], ['

[0.17044438 0.58431431 0.68588957] [['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xsph', 3, 6], ['Xdinp*Xldh', 4, 5], ['Xdinp*Xsph', 4, 6], ['Xldh*Xsph', 5, 6]]
[0.2091519  0.55469695 0.70289185] [['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xstabiliser*Xldh', 3, 5], ['Xstabiliser*Xsph', 3, 6], ['Xdinp*Xldh', 4, 5], ['Xdinp*Xsph', 4, 6], ['Xldh*Xsph', 5, 6]]
[0.2456805  0.62183484 0.75641931] [['Xstabiliser', 3], ['Xdinp', 4], ['Xldh', 5], ['Xsph', 6], ['Xstabiliser*Xdinp', 3, 4], ['Xstabiliser*Xldh', 3, 5], ['Xstabiliser*Xsph', 3, 6], ['Xdinp*Xldh', 4, 5], ['Xdinp*Xsph', 4, 6], ['Xldh*Xsph', 5, 6]]
[0.21793587 0.25274041 0.24595469] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4]]
[0.19343486 0.25305677 0.24454964] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1]]
[0.13641538 0.17093015 0.2272228 ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 

[ 0.06807087 -0.41567645 -0.37782221] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfiller*Xdinp', 1, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.30167879 -0.03126768  0.2180791 ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4]]
[ 0.34956477 -0.28794188  0.07894862] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.272908   -0.26601613  0.00518701] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[0.02444361 0.12723436 0.22522098] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3]]
[0.15914039 0.11231157 0.14122065] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2]

[ 0.01420126 -0.10120796  0.16711896] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4]]
[ 0.06456587 -0.40604421 -0.44345572] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xdinp', 1, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.23999762 -0.03128183  0.21032354] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4]]
[ 0.30838648 -0.31095398  0.07659902] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.15298    -0.27671918  0.00756886] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.17461198 -0.03390023  0.02560707] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 

[ 0.02153191 -0.18604842  0.01007187] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xfr', 1, 2]]
[-0.00466913 -0.18209734  0.13066264] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xstabiliser', 1, 3]]
[-0.13123225  0.1254364   0.15469563] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xdinp', 1, 4]]
[0.20222898 0.22351705 0.28607657] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfr*Xstabiliser', 2, 3]]
[-0.11580074 -0.16004877  0.12457775] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0,

[-0.19166792  0.15990221 -0.03426633] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4]]
[0.26192522 0.20829073 0.10606384] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xstabiliser', 2, 3]]
[ 0.17534694 -0.50295859 -0.23294428] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xdinp', 2, 4]]
[ 0.27453809 -0.37898503 -0.02964417] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xdinp', 3, 4]]
[-0.04223717  0.1969786  -0.02891572] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1],

[ 0.30392137 -0.00821758  0.03851073] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfr*Xstabiliser', 2, 3]]
[ 0.06397808 -0.45262692 -0.23441168] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfr*Xdinp', 2, 4]]
[ 0.26102305 -0.27042508 -0.05415243] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xstabiliser*Xdinp', 3, 4]]
[-0.18075779  0.09662157 -0.03365849] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4]]
[0.23310786 0.10550168 0.11027252] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser

[0.25565602 0.19199912 0.19876145] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xstabiliser', 2, 3]]
[ 0.18133122 -0.14408581  0.11702599] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xdinp', 2, 4]]
[ 0.24705674 -0.3172519  -0.05897502] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xdinp', 3, 4]]
[0.07337377 0.20809645 0.19122473] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3]]
[-0.04678956 -0.0788419   0.12846092] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xst

[ 0.00866665 -0.0289621   0.20745333] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4]]
[ 0.02593464 -0.41037042 -0.43608079] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4]]
[-0.07179327 -0.25612615 -0.25168339] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.30233303 -0.21238002  0.00076112] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.18585586 -0.24820426 -0.23460428] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], 

[ 0.16070713 -0.13136143  0.09305947] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xfr', 1, 2], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4]]
[ 0.29495563 -0.27124969 -0.01377196] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xfr', 1, 2], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.01948676 -0.33893666 -0.04466583] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xfr', 1, 2], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[-0.02446257  0.19264523  0.11405229] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3]]
[-0.15147842 -0.14029618  0.07361276] [['Xpvc', 0], ['Xfiller'

[-0.05869054 -0.35725737 -0.14548082] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.31227316 -0.28429952 -0.02026384] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xstabiliser', 0, 3], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[-0.23769427  0.1248162  -0.05143324] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4]]
[0.25982835 0.20234634 0.04512511] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xstabiliser', 2, 3]]
[ 0.17399978 -0.5030623  -0.23704887] [

[-0.13848557 -0.4550849  -0.25700581] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4]]
[-0.10289158 -0.35300195 -0.47422481] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xdinp', 1, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.09051579 -0.40149191 -0.24379216] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4]]
[ 0.22647587 -0.31554103  0.0468507 ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.06062472 -0.32209352 -0.20255933] [['Xpvc', 0], ['Xfille

[ 0.13811026 -0.06301182  0.1156327 ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4]]
[ 0.18389716 -0.28751337 -0.285039  ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4]]
[-0.02390677 -0.27080411 -0.26218331] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.19809052 -0.22174624 -0.00817326] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xfr', 1, 2], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.00979805 -0.02948333  0.19766966] [['Xpvc', 0], ['Xfiller', 1]

[ 0.03938104 -0.35110476 -0.30359835] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.33499388 -0.29898413 -0.16052208] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[-0.06867156 -0.3937717  -0.3123885 ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4]]
[-0.06010291 -0.40791399 -0.55095484] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4]]
[-0.10145973 -0.35260642 -0.32370694] [['X

[-0.11703808  0.03212516  0.01632249] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3]]
[-0.29879009 -0.42121697 -0.25477613] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4]]
[-0.20047287 -0.30839509 -0.41066283] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.14334011 -0.34418225 -0.22355267] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdi

[-0.11707686 -0.40520865 -0.20510383] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.30085402 -0.33846592 -0.1328266 ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[-0.05415674 -0.0596211   0.09341271] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3]]
[-0.30527788 -0.12791203  0.08119656] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xfr', 1, 2], ['Xfiller*X

[-0.03246484 -0.33864025 -0.5357779 ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.08233291 -0.39824103 -0.29096982] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4]]
[ 0.22576997 -0.3419534  -0.01282022] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4]]
[-0.03379688 -0.25287351 -0.16168755] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xst

[ 0.30276623 -0.29875655 -0.13311237] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[-0.06534915 -0.43524771 -0.44869326] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4]]
[-0.06409036 -0.50843744 -0.72194853] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4]]
[-0.00709156 -0.2316591  -0.20320238] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3

[ 0.02111711 -0.07726533  0.15116512] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4]]
[ 0.05690323 -0.63999023 -0.49953689] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4]]
[-0.03818275 -0.27638587 -0.18021961] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[ 0.05928305 -0.24657942 -0.06079054] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc

[ 0.30111802 -0.33314668 -0.2261619 ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[-0.2599782  -0.37613669 -0.376291  ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[-0.07969098 -0.37178675 -0.45290567] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[-0.17882062 -0.32865251 -0.30363595] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 

[-0.63665749 -0.34245806 -0.35800692] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xfr', 1, 2], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4], ['Xstabiliser*Xdinp', 3, 4]]
[-0.06876247 -0.49947396 -0.51133438] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xdinp', 2, 4]]
[-0.0452994  -0.75671017 -0.78975434] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xdinp', 4], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xdinp', 0, 4], ['Xfiller*Xstabiliser', 1, 3], ['Xfiller*Xdinp', 1, 4], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xdinp', 3, 4]]
[-0.01884393 -0.32406092 -0.32121338] [['Xpvc', 0], ['Xfille

[0.12887927 0.17223875 0.17885794] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5]]
[-0.0423253   0.18232904  0.20947231] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1]]
[0.08225042 0.20161007 0.19428441] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfr', 0, 2]]
[0.14645528 0.1581431  0.19146673] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3]]
[-3.39949166  0.38200511  0.39878193] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xldh', 0, 5]]
[0.12310907 0.1251252  0.00951435] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfiller*Xfr', 1, 2]]
[0.12232485 0.16119836 0.14291685] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfiller*Xstabiliser', 1, 3]]
[0.0148787  0.17766554 0.11435459] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], 

[-0.06957082  0.14423305  0.01109887] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xfr', 1, 2]]
[-0.01182429  0.15769787  0.15537916] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xstabiliser', 1, 3]]
[0.07101891 0.20371373 0.08940188] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfiller*Xldh', 1, 5]]
[0.09299775 0.27572091 0.25048652] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfr*Xstabiliser', 2, 3]]
[-0.00461007  0.17432802  0.18885025] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xfr*Xldh', 2, 5]]
[-0.49538488  0.30677346  0.46948243] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 

[-3.51688791  0.30683742  0.18985457] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xfr', 1, 2]]
[-3.40652929  0.33617759  0.35406011] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xstabiliser', 1, 3]]
[-2.24283786  0.47539154  0.44161074] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xldh', 1, 5]]
[-3.89168487  0.43492446  0.44122807] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xfr*Xstabiliser', 2, 3]]
[-3.42377972  0.35225028  0.38617658] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xfr*Xldh', 2, 5]]
[-2.23201737  0.4801614   0.53780451] [['Xpvc', 0], ['Xfiller', 1

[-0.0618898  -0.069029   -0.13665521] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xfr', 1, 2]]
[-0.06845227 -0.07183452  0.10725897] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xstabiliser', 1, 3]]
[0.00974185 0.08948585 0.07959965] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xldh', 1, 5]]
[0.08974076 0.17453904 0.24724191] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfr*Xstabiliser', 2, 3]]
[-0.01117252  0.09661827  0.18564819] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xfr', 0, 2], ['Xp

[-0.60373621  0.37611112  0.43246361] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xstabiliser', 0, 3], ['Xfr*Xldh', 2, 5], ['Xstabiliser*Xldh', 3, 5]]
[-3.53504914  0.31733152  0.21621481] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3]]
[-2.84706215  0.419885    0.20342789] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xldh', 1, 5]]
[-4.11126373  0.40561955  0.25834631] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xfr', 1, 2], ['Xfr*Xstabiliser', 2, 3]]
[-3.57422057  0.32759901  0.20077776] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfiller', 0, 1], ['Xpvc*Xldh', 0, 5], ['Xf

[-0.33267915  0.39730459  0.45580985] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xstabiliser', 1, 3], ['Xstabiliser*Xldh', 3, 5]]
[-0.03148116  0.19999408  0.1434829 ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xldh', 1, 5], ['Xfr*Xstabiliser', 2, 3]]
[-0.07467019  0.14222399  0.08313437] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xldh', 1, 5], ['Xfr*Xldh', 2, 5]]
[-0.31935262  0.36550353  0.51382844] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller*Xldh', 1, 5], ['Xstabiliser*Xldh', 3, 5]]
[0.05504482 0.19681719 0.17077159] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xfr', 0, 2], ['Xpvc*Xstabiliser',

[-0.8619594   0.59159054  0.73443052] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xfiller*Xldh', 1, 5], ['Xstabiliser*Xldh', 3, 5]]
[-4.15169093  0.41890128  0.42223144] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xldh', 2, 5]]
[-2.43667035  0.57669549  0.62897201] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xldh', 3, 5]]
[-2.17517066  0.4772351   0.52052168] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xpvc*Xldh', 0, 5], ['Xfr*Xldh', 2, 5], ['Xstabiliser*Xldh', 3, 5]]
[-0.11408605  0.12542083 -0.1834482 ] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xpvc*Xstabiliser', 0, 3], ['Xfiller

[-0.22227818  0.17878521  0.25103712] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xstabiliser', 1, 3], ['Xfr*Xldh', 2, 5], ['Xstabiliser*Xldh', 3, 5]]
[ 0.07323855  0.18709693 -0.09094712] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xldh', 1, 5], ['Xfr*Xstabiliser', 2, 3], ['Xfr*Xldh', 2, 5]]
[-0.22770886  0.36937021  0.48745462] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xldh', 1, 5], ['Xfr*Xstabiliser', 2, 3], ['Xstabiliser*Xldh', 3, 5]]
[-0.39882197  0.2347402   0.32561368] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfiller*Xfr', 1, 2], ['Xfiller*Xldh', 1, 5], ['Xfr*Xldh', 2, 5], ['Xstabiliser*Xldh', 3, 5]]
[-0.11953745  0.26233175  0.37349977] [['Xpvc', 0], ['Xfiller', 1], ['Xfr', 2], ['Xstabiliser', 3], ['Xldh', 5], ['Xfiller*Xfr', 1, 2], ['Xfr*Xstabiliser',

KeyboardInterrupt: 

In [ ]:
df = pd.DataFrame(total_subset)
df.to_csv("Toatal_model_subset_"  + response + ".csv")

dff = pd.DataFrame(model_subset)
dff.to_csv("limited_model_subset_"  + response + ".csv")

In [ ]:
# plt.plot(CN_hist, AIC_hist, 'r*')
# plt.axis([0, 2000, 12, 20])
# plt.xlabel('CN')
# plt.ylabel('AIC')
# plt.show()

In [ ]:
# plt.plot(VIF_max_hist, AIC_hist1, 'r*')
# plt.show()

In [ ]:
# plt.scatter(CN_hist1, AIC_hist1, c = VIF_max_hist, vmin=0, vmax=50)
# # plt.axis([0, 1000, 12, 20])
# plt.xlabel('CN')
# plt.ylabel('AIC')
# plt.colorbar()
# # plt.set_label('VIF')
# plt.show()

In [ ]:
# from mpl_toolkits.mplot3d import Axes3D

# fig = plt.figure()
# ax = Axes3D(fig)

# ax.scatter(CN_hist1,VIF_max_hist, AIC_hist1)
# plt.xlabel('CN')
# plt.ylabel('VIF')
# ax.set_zlabel('AIC')
# # plt.axis([0, 1000, 12, 18])
# # plt.colorbar()
# plt.show()

In [ ]:
# len(model_subset)

In [ ]:
# for i in model_subset:
#     if i[2] < 550 and i[2] > 450:
#         a = []
#         for j in i[0]:
#             a.append(j[0])
#         print('----model:', a, 'AIC', round(i[1], 3), 'CN:', round(i[2], 3), 'vif_max:', round(i[3], 3), 'R2:', round(i[4], 3), '----'
#              )
        

# 